project:
  type: website


website:
  title: "scheduled-docs"
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    theme: cosmo
