project:
  type: website


website:
  title: "scheduled-docs"
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo

scheduled-docs:
  draft-after: "1/2/24" # can use "system-time" or manually set datetime using format "1/2/24"
  timezone: "-07:00" # GMT offset in +/-hh:mm does not adjust for daylight savings
  docs:
    - href: "posts/post-1.qmd"
      date: 1/1/24
    - href: "posts/post-2.qmd"
      date: 1/3/24
    - href: "posts/post-3.qmd"
      date: 1/5/24


# alternative structure showing the `docs:` can be nested anywhere in `scheduled-docs`:
# scheduled-docs:
#   draft-after: "1/4/24" # can use "system-time" or manually set datetime using format "1/2/24"
#   timezone: "-07:00" # GMT offset in +/-hh:mm does not adjust for daylight savings
#   schedule:
#     - type: Part A
#       docs:
#         - href: "posts/post-1.qmd"
#           date: 1/1/24
#     - type: Part B
#       mods:
#         docs:
#           - href: "posts/post-2.qmd"
#             date: 1/3/24
#           - href: "posts/post-3.qmd"
#             date: 1/5/24



