project:
  type: website


website:
  title: "scheduled-docs"
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
metadata-files: 
  - scheduled-docs_files/draft-list.yml
  - scheduled-docs_files/sidebar-contents.yml
        
format:
  html:
    theme: cosmo
